# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: postgresql
  encoding: utf8
  database: d3nhpl268ua9sr
  username: kmyzonzdmsbnxc
  password: c434bdb56fbe741f7fe56b79bee71f6a65e3c682477bad8c0d2594a9f4b3b065
  host: ec2-23-23-225-12.compute-1.amazonaws.com
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: d3nhpl268ua9sr
  username: kmyzonzdmsbnxc
  password: c434bdb56fbe741f7fe56b79bee71f6a65e3c682477bad8c0d2594a9f4b3b065
  host: ec2-23-23-225-12.compute-1.amazonaws.com
  port: 5432
  
production:
  adapter: postgresql
  encoding: utf8
  database: d3nhpl268ua9sr
  username: kmyzonzdmsbnxc
  password: c434bdb56fbe741f7fe56b79bee71f6a65e3c682477bad8c0d2594a9f4b3b065
  host: ec2-23-23-225-12.compute-1.amazonaws.com
  port: 5432
